### ISSUE TITLE
Bar in Portrait

### ISSUE THREAD

**Issue by Javierusan** [Legitamine/metanthropes#270]
Hello, in PF2e I don't see the HP bar in the portrait (left or right), do I have to configure something? Thank you.

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/w3KJnkn5/Sin-t-tulo.jpg' border='0' alt='Sin-t-tulo'/></a>

**Comment by bofhgr** [comment]
I am confused as to what does this have to do with Metanthropes?

**Comment by Javierusan** [comment]
> I am confused as to what does this have to do with Metanthropes?

Sorry, I was in the wrong place. If you can, delete this post. Sorry. Thank you.

**Comment by bofhgr** [comment]
No problem!
